#!/usr/bin/env bash

# Name of the buildx environment
BUILDX_ENV_NAME="buildx"

# Function to check if buildx environment exists
check_buildx_env() {
    if ! docker buildx inspect "$BUILDX_ENV_NAME" >/dev/null 2>&1; then
        echo "Creating buildx environment: $BUILDX_ENV_NAME"
        docker buildx create --use --name "$BUILDX_ENV_NAME" || {
            echo "Failed to create buildx environment."
            exit 1
        }
    else
        echo "Buildx environment '$BUILDX_ENV_NAME' is ready."
    fi
}

check_buildx_env
docker buildx build --no-cache --push \
        --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/arm/v6,linux/ppc64le,linux/s390x,linux/386 \
        -t thenaim/ansible-runner-with-playbook:latest .

docker run --rm -it thenaim/ansible-runner-with-playbook:latest sh
