---
- name: Install packages on a remote Ubuntu server
  hosts: all
  become: yes  # This elevates privileges to run tasks that require sudo

  tasks:
    - name: Convert JSON string to list
      set_fact:
        packages: "{{ packages_list | from_json }}"
      vars:
        packages_list: "{{ packages }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache is considered valid for 1 hour

    - name: Debug packages variable
      ansible.builtin.debug:
        var: packages

    - name: Install specified packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
